version: '3.8'
services:
    db:
        image: postgres
        container_name: "pg_container"
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=desafio_01
        ports:
          - "5432:5432"
        volumes:
          - "./db:/var/lb/postgres/data/"
